# Generated by Django 5.1.6 on 2025-02-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='City',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
